[tool.poetry]
name = "discarch"
version = "0.1.0"
description = "The Dicussion Archiver"
authors = ["Moon Cult"]

[tool.poetry.dependencies]
python = "^3.7"
slackclient = "^2.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
